services:
  ui-kit:
    image: ui-kit-builder
    build:
      context: modules/ui-kit
      dockerfile: Dockerfile

  ws-client:
    image: ws-client-builder
    build:
      context: modules/ws-client
      dockerfile: Dockerfile

  base:
    image: base
    build:
      context: .
      dockerfile: Dockerfile

  client:
    image: client
    build:
      context: apps/client
      dockerfile: Dockerfile
    depends_on:
      - base
    ports:
      - "5000:4173"
