default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "DigiTask.xcodeproj")
    build_app(workspace: "DigiTask.xcworkspace", scheme: "DigiTask")
    upload_to_app_store(skip_metadata: true, skip_screenshots: true)
  end
end
