default_platform(:ios)

team_id("MCTUG52M88")

platform :ios do
  before_all do
    ENV["FASTLANE_TEAM_ID"] = "MCTUG52M88"
  end

  desc "Build and export IPA with manual signing"
  lane :build do
    match(type: "adhoc", readonly: true)

    build_app(
      workspace: "DigiTask.xcworkspace",
      scheme: "DigiTask",
      configuration: "Release",
      export_method: "ad-hoc",
      export_team_id: "MCTUG52M88",
      export_options: {
        provisioningProfiles: {
          "com.oneirogroup.digitask" => "DigiTask"
        },
        signingStyle: "manual",
        teamID: "MCTUG52M88",
        uploadBitcode: false,
        uploadSymbols: true
      }
    )
  end
end
